@host=http://localhost:5284
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOWJhMTFlNC1hNWNlLTQyMjEtYmFhMi0xY2M2ZGNjY2FmNGQiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjMxYjM1OTgzLTZhNGQtNDZlZS05NWM5LTIyZjgwZDkyNTUxYyIsImV4cCI6MTY4MDQwMzQ1NSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.jhzTjAG77HQMsO92l86VrP0B6UvsLk6ueLTVLpoxnUM
GET {{host}}/dinners
Authorization: Bearer {{token}}